spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: rootroot

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Комаров Богдан
  copyrightFrom: 2021