server:
  error:
    whitelable:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: rootroot

  jpa:
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none

  mail:
    host: smtp.google.com
    username: bogdankomarov.bk@gmail.com
    password:
    properties:
      mail:
        debug: true
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true

  flyway:
    enabled: true
    schemas: blogengine
    baselineOnMigrate: true

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Комаров Богдан
  copyrightFrom: 2021
captcha:
  lifetimeInMinutes: 3600
upload:
  path: upload/
